language: php

sudo: true

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  fast_finish: true

  allow_failures:
    - php: hhvm

cache:
  directories:
    - laravel

install:
  # create a new database for the hyn connection
  - export DB_USERNAME=travis DB_DATABASE=hyn DB_PASSWORD= QUEUE_DRIVER=sync
  - mysql -e 'create database hyn;' -uroot
  - mysql -e "grant all privileges on *.* to 'travis'@'localhost' with grant option;" -uroot
  - export PACKAGE_PROVIDER=Kevupton\\Bookings\\Providers\\BookingsServiceProvider::class
  - bin/setup.sh

script:
  - cd laravel
    && composer update
    && php artisan vendor:publish
    && php artisan migrate
    && phpunit vendor/kevupton

  # run the script calling unit tests and so on