language: php

sudo: true

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  fast_finish: true

  allow_failures:
    - php: hhvm

cache:
  directories:
    - laravel

before_install:
  - composer create-project laravel/laravel;
  - cd laravel;
  - composer require kevupton/bookings
  - awk '/'\''providers'\'' \=\> \[/ { print; print "Kevupton\\Bookings\\Providers\\BookingsServiceProvider::class,"; next }1'
           config/app.php > config/app.php
  - composer update
  - php artisan vendor:publish
  - php artisan migrate

install:
  # create a new database for the hyn connection
  - mysql -e 'create database hyn;' -uroot
  - mysql -e "grant all privileges on *.* to 'travis'@'localhost' with grant option;" -uroot
  # set global variables
  - export DB_USERNAME=travis DB_DATABASE=hyn DB_PASSWORD= QUEUE_DRIVER=sync

script:
  - composer update
  - php artisan vendor:publish #puts all migrations from packages into migrations folder
  - php artisan migrate
  - phpunit vendor/kevupton


  # run the script calling unit tests and so on