language: php

sudo: true

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  fast_finish: true

  allow_failures:
    - php: hhvm

cache:
  directories:
    - laravel

install:
  # set the global github token, so connections won't be cancelled
  - composer config -g github-oauth.github.com $GITHUB_TOKEN
  # create a new database for the hyn connection
  - mysql -e 'create database hyn;' -uroot
  - mysql -e "grant all privileges on *.* to 'travis'@'localhost' with grant option;" -uroot
  # create a new laravel project in the subfolder laravel (default composer behaviour)
  - if [ ! -d "laravel" ]; then
      composer create-project laravel/laravel &&
      cd laravel &&
      composer require kevupton/booking &&
      awk '/'\''providers'\'' \=\> \[/ { print; print "Kevupton\\Bookings\\Providers\\BookingsServiceProvider::class,"; next }1' config/app.php &&
      php artisan vendor:publish &&
      php artisan migrate;
    fi
  # set global variables
  - export DB_USERNAME=travis DB_DATABASE=hyn DB_PASSWORD= QUEUE_DRIVER=sync

script:
  - composer update
  - php artisan vendor:publish #puts all migrations from packages into migrations folder
  - php artisan migrate
  - phpunit vendor/kevupton


  # run the script calling unit tests and so on