language: php

sudo: true

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  fast_finish: true

  allow_failures:
    - php: hhvm

cache:
  directories:
    - laravel

install:
  # create a new database for the hyn connection
  - export DB_USERNAME=travis DB_DATABASE=hyn DB_PASSWORD= QUEUE_DRIVER=sync
  - mysql -e 'create database hyn;' -uroot
  - mysql -e "grant all privileges on *.* to 'travis'@'localhost' with grant option;" -uroot

  - [ ! -d "laravel" ]
      && composer create-project laravel/laravel
      && composer update
      && cd laravel
      && composer require kevupton/bookings
      && echo "$(awk '/'\''providers'\'' \=\> \[/ { print; print "Kevupton\\Bookings\\Providers\\BookingsServiceProvider::class,"; next }1'
           config/app.php)" > config/app.php
      && php artisan vendor:publish
      && php artisan migrate || true


script:
  - composer update
  - php artisan vendor:publish #puts all migrations from packages into migrations folder
  - php artisan migrate
  - phpunit vendor/kevupton


  # run the script calling unit tests and so on